version: '3.8'

services:
  app:
    image: python:3.9
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: tail -f /dev/null
    build: 
      context: .
      dockerfile: Dockerfile
