name: PR Health Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
            run: |
            curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
            pipenv sync --dev

      - name: Run health check script
        run: pipenv run linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
