name: "ladybug linter"

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]

jobs:
  linter: # job_id
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./ # This is the path to the action.yml file
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          label: "hello"
          name: "Ladybug Linter"